services:
  front:
    build:
      dockerfile: Dockerfile
    env_file:
      - app/.env.production
    ports:
      - "8080:8080"
    volumes:
      - ~/.aws/credentials:/home/nextjs/.aws/credentials:ro
      - ~/.aws/config:/home/nextjs/.aws/config:ro
      - ~/.aws/sso/cache:/home/nextjs/.aws/sso/cache:rw
